export type Product = {
    id: number;
    name: string;
    brand: string;
    category1: string;
    category2: string;
    size: string;
    price: number;
    purchasePrice: number;
    image: string;
    colors: string[];
    conditionGrade: string;
    description: string;
    createdAt: string;
    status: string;
    brandSize : string;
    discountRate : number;
    shape : string;
    season : string;
    conditionDetail: string;
  //  [key: string]: any;
  };